# Copyright (C) 2001-2022, Python Software Foundation
# This file is distributed under the same license as the Python package.
#
# Translators:
# Matt Wang <mattwang44@gmail.com>, 2022
#
msgid ""
msgstr ""
"Project-Id-Version: Python 3.10\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-06-20 18:08+0800\n"
"PO-Revision-Date: 2022-01-31 21:41+0800\n"
"Last-Translator: Matt Wang <mattwang44@gmail.com>\n"
"Language-Team: Chinese - TAIWAN (https://github.com/python/python-docs-zh-"
"tw)\n"
"Language: zh_TW\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Poedit 3.0.1\n"

#: ../../library/asyncio-exceptions.rst:8
msgid "Exceptions"
msgstr "例外"

#: ../../library/asyncio-exceptions.rst:10
msgid "**Source code:** :source:`Lib/asyncio/exceptions.py`"
msgstr "**原始碼：**\\ :source:`Lib/asyncio/exceptions.py`"

#: ../../library/asyncio-exceptions.rst:16
msgid "The operation has exceeded the given deadline."
msgstr "該操作已超過規定的截止時間。"

#: ../../library/asyncio-exceptions.rst:19
msgid ""
"This exception is different from the builtin :exc:`TimeoutError` exception."
msgstr "這個例外與內建 :exc:`TimeoutError` 例外不同。"

#: ../../library/asyncio-exceptions.rst:25
msgid "The operation has been cancelled."
msgstr "該操作已被取消。"

#: ../../library/asyncio-exceptions.rst:27
msgid ""
"This exception can be caught to perform custom operations when asyncio Tasks "
"are cancelled.  In almost all situations the exception must be re-raised."
msgstr ""
"當 asyncio Task 被取消時，可以捕獲此例外以執行客製化操作。在幾乎所有情況下，"
"該例外必須重新被引發。"

#: ../../library/asyncio-exceptions.rst:33
msgid ":exc:`CancelledError` is now a subclass of :class:`BaseException`."
msgstr ":exc:`CancelledError` 現在是 :class:`BaseException` 的子類別。"

#: ../../library/asyncio-exceptions.rst:38
msgid "Invalid internal state of :class:`Task` or :class:`Future`."
msgstr ":class:`Task` 或 :class:`Future` 的無效內部狀態。"

#: ../../library/asyncio-exceptions.rst:40
msgid ""
"Can be raised in situations like setting a result value for a *Future* "
"object that already has a result value set."
msgstr "可以在像是為已設定結果值的 *Future* 物件設定結果值的情況下引發。"

#: ../../library/asyncio-exceptions.rst:46
msgid ""
"The \"sendfile\" syscall is not available for the given socket or file type."
msgstr "\"sendfile\" 系統呼叫不適用於給定的 socket 或檔案型別。"

#: ../../library/asyncio-exceptions.rst:49
msgid "A subclass of :exc:`RuntimeError`."
msgstr "一個 :exc:`RuntimeError` 的子類別。"

#: ../../library/asyncio-exceptions.rst:54
msgid "The requested read operation did not complete fully."
msgstr "請求的讀取操作未全部完成。"

#: ../../library/asyncio-exceptions.rst:56
msgid "Raised by the :ref:`asyncio stream APIs<asyncio-streams>`."
msgstr "由 :ref:`asyncio 串流 APIs <asyncio-streams>` 引發。"

#: ../../library/asyncio-exceptions.rst:58
msgid "This exception is a subclass of :exc:`EOFError`."
msgstr "此例外是 :exc:`EOFError` 的子類別。"

#: ../../library/asyncio-exceptions.rst:62
msgid "The total number (:class:`int`) of expected bytes."
msgstr "預期的位元組總數 (\\ :class:`int`\\ )。"

#: ../../library/asyncio-exceptions.rst:66
msgid "A string of :class:`bytes` read before the end of stream was reached."
msgstr "串流結束之前讀取的 :class:`bytes` 字串。"

#: ../../library/asyncio-exceptions.rst:71
msgid "Reached the buffer size limit while looking for a separator."
msgstr "在查詢分隔符號 (separator) 時達到緩衝區 (buffer) 大小限制。"

#: ../../library/asyncio-exceptions.rst:73
msgid "Raised by the :ref:`asyncio stream APIs <asyncio-streams>`."
msgstr "由 :ref:`asyncio 串流 APIs <asyncio-streams>` 引發。"

#: ../../library/asyncio-exceptions.rst:77
msgid "The total number of to be consumed bytes."
msgstr "要消耗的位元組總數。"
