# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2018, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.10\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-06-20 18:08+0800\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: zh_TW\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../../library/asyncio-exceptions.rst:8
msgid "Exceptions"
msgstr ""

#: ../../library/asyncio-exceptions.rst:10
msgid "**Source code:** :source:`Lib/asyncio/exceptions.py`"
msgstr ""

#: ../../library/asyncio-exceptions.rst:16
msgid "The operation has exceeded the given deadline."
msgstr ""

#: ../../library/asyncio-exceptions.rst:19
msgid ""
"This exception is different from the builtin :exc:`TimeoutError` exception."
msgstr ""

#: ../../library/asyncio-exceptions.rst:25
msgid "The operation has been cancelled."
msgstr ""

#: ../../library/asyncio-exceptions.rst:27
msgid ""
"This exception can be caught to perform custom operations when asyncio Tasks "
"are cancelled.  In almost all situations the exception must be re-raised."
msgstr ""

#: ../../library/asyncio-exceptions.rst:33
msgid ":exc:`CancelledError` is now a subclass of :class:`BaseException`."
msgstr ""

#: ../../library/asyncio-exceptions.rst:38
msgid "Invalid internal state of :class:`Task` or :class:`Future`."
msgstr ""

#: ../../library/asyncio-exceptions.rst:40
msgid ""
"Can be raised in situations like setting a result value for a *Future* "
"object that already has a result value set."
msgstr ""

#: ../../library/asyncio-exceptions.rst:46
msgid ""
"The \"sendfile\" syscall is not available for the given socket or file type."
msgstr ""

#: ../../library/asyncio-exceptions.rst:49
msgid "A subclass of :exc:`RuntimeError`."
msgstr ""

#: ../../library/asyncio-exceptions.rst:54
msgid "The requested read operation did not complete fully."
msgstr ""

#: ../../library/asyncio-exceptions.rst:56
msgid "Raised by the :ref:`asyncio stream APIs<asyncio-streams>`."
msgstr ""

#: ../../library/asyncio-exceptions.rst:58
msgid "This exception is a subclass of :exc:`EOFError`."
msgstr ""

#: ../../library/asyncio-exceptions.rst:62
msgid "The total number (:class:`int`) of expected bytes."
msgstr ""

#: ../../library/asyncio-exceptions.rst:66
msgid "A string of :class:`bytes` read before the end of stream was reached."
msgstr ""

#: ../../library/asyncio-exceptions.rst:71
msgid "Reached the buffer size limit while looking for a separator."
msgstr ""

#: ../../library/asyncio-exceptions.rst:73
msgid "Raised by the :ref:`asyncio stream APIs <asyncio-streams>`."
msgstr ""

#: ../../library/asyncio-exceptions.rst:77
msgid "The total number of to be consumed bytes."
msgstr ""
